Disclaimer - Project from 2021

Hi! This repository details my work on a DIY MIDI Drum-pad powered by an Arduino UNO.

Required Materials:

|===
| ID | Part name      | Part number | Quantity
| A1 | Arduino Uno   | A000066    | 1
| R1 | 10k Resistor   |             | 3
| B1 | Breadboards with Power Rails | 3
| B2 | Tactile Switches  |    | 24
|===

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact maheshwarim297 https://id.arduino.cc/maheshwarim297

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
