Disclaimer - Project from 2021

== DIY Arduino MIDI Drum-pad 

Hi! This repository details my work on a DIY MIDI Drum-pad powered by an Arduino UNO. 

Musical Instrument Digital Interface (MIDI) is a digital language used to denote musical notes, whether in DAW (Digital Audio Workstation) piano rolls, or to and from physical interfaces like piano keyboards and drum pads to these DAWs. This project was about creating a DIY MIDI instrument that can work as a physical drum pad with 24 buttons, each of which can be linked to either seperate drum sounds or notes for other instruments. 

Every button is linked to a unique MIDI note, corresponding to a different note on an 88-key keyboard. On each press, a serial message is processed and sent to the computer through the Arduino Uno, to be interpreted by the host computer. To convert this serial message to MIDI, an app such as Hairless Serial to MIDI must be run. After this, the Arduino instrument should be recognized by the DAW, and you can start making beats!   

== Required Materials for Circuit:

|===
| ID | Part name      | Part number | Quantity
| A1 | Arduino Uno   | A000066    | 1
| B1 | Tactile Switches | | 24
| R1 | 10k Resistor   |             | 3
| B2 | Breadboards with Power Rails | | 3
|

|===

=== Folder structure

....
 Arduino-MIDI-Keyboard                => Arduino sketch folder
  ├── 24_button_midi.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a MIT License.

=== Contributing
To contribute to this project please contact maheshwarim297 https://id.arduino.cc/maheshwarim297

=== BOM
Add the bill of the materials you need for this project.


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
