*Disclaimer - Project from 2021, in the process of redocumenting, will provide images and schematics soon*

== DIY Arduino MIDI Drum-pad 

Hi! This repository details my work on a DIY MIDI Drum-pad powered by an Arduino UNO. 

*Musical Instrument Digital Interface (MIDI)* is a digital language used to denote musical notes, whether in DAW (Digital Audio Workstation) piano rolls, or to and from physical interfaces like piano keyboards and drum pads to these DAWs.

This project was about creating a DIY MIDI instrument that can work as a physical drum pad with 24 buttons, each of which can be linked to either seperate drum sounds or notes for other instruments. 

Every button is linked to a unique MIDI note, corresponding to a different note on an 88-key keyboard. On each press: 

1. The Arduino finds what key the button press came from, and attaches it to the proper MIDI value
2. A serial message is processed and sent to be interpreted by the host computer
3. An interpreter like https://projectgus.github.io/hairless-midiserial[Hairless Serial to MIDI] converts these signals to MIDI notes for the DAW
4. After this, the Arduino instrument should be recognized by the DAW, and you can start making beats!   


== Circuit description 

The first challenge of a project like this was to find how to connect a large amount of sensors to the limited amount of Digital Input/Output pins on my Arduino Uno board. One possible solution would be to buy and use multiplexers. However, I used what's known as a *Matrix Circuit*, allowing me to make more efficient use of the existing I/O pins. 

*To use a Matrix circuit:* 

* Each column was connected to one unique output pin
* Each row was connected to a unique input pin 

To be able to discern input from keys, signals were sent to one output pin at a time. If you see the attached circuit schematics, each button press allows for voltage to flow towards the input pin corresponding to it's own row. To process: 

* Signal sent to Column 0 
* Input recieved at Row 2 
* Button press must have been from button at (2, 0) corresponding to MIDI note 61

This message is then pushed as a serial message to the host computer. 

== Required Materials for Circuit:

|===
| ID | Part name      | Part number | Quantity
| A1 | Arduino Uno   | A000066    | 1
| B1 | Tactile Switches | | 24
| R1 | 10k Resistor   |             | 3
| B2 | Breadboards with Power Rails | | 3
|

|===

=== Folder structure

....
 Arduino-MIDI-Keyboard                => Arduino sketch folder
  ├── 24_button_midi.ino       => main Arduino file
  ├── schematics.png      => an image of the required schematics
  ├── layout.png          => an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a MIT License.

=== Contributing
To contribute to this project please contact maheshwarim297 https://id.arduino.cc/maheshwarim297


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
